#!/bin/sh -
#
# EXAMPLES:
#
# 1) To get the CIDR for <NAME>:
#
#   /usr/bin/env IFCONFIG_FORMAT=inet:cidr /sbin/ifconfig <NAME> | /usr/local/bin/jq '.lines[4]' | /usr/bin/grep -soE 'inet (\.?[[:digit:]]{1,3}){4}/[[:digit:]]{1,2}'
#
# 2) To test if <NAME> exists (200) or not (500):
#
#   /usr/bin/env IFCONFIG_FORMAT=inet:cidr /sbin/ifconfig <NAME> | /usr/local/bin/jq '.status'
#

_main() {
  local CMD="$@";
  if [ -z "$CMD" ]; then
    echo '<$@: CMD>' >> /dev/stderr; return 1;
  fi

  /usr/local/bin/curl -X POST \
                      -d "{\"command\": \"${CMD}\"}" \
                      -H "Content-type: application/json" \
                      -s \
                      http://127.0.0.1/run
}
_main "$@"
